type = "service_account"
project_id = "streamlit-user-auth"
private_key_id = "bafb09360eeddcd9bbfd032bd101584fc9df4a6c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDtPelOunRASVtW
H+mM/kdp+I1LcQUgrHfLNQRD8+lLU53U6UiuFG2RphPZQ5MHTQ0GNG+EDFhi8h/3
Md3jGCGFd0ndlL/TLVt94dHKR9qehP6qaR1bEgRw3kF/UDz1LHQQgEBQqs/xRAr9
C1Co4xab84l6juyvjudwUAC3U+Zuvq0jvJJkXxvvNTBDhOOCm9PK6NCLzcYZ2Z73
/TZM4rWyGnhu4sR5r4ELj3wIPD6siRbD3WpZ97dtL7wdPj3eh5RDk33w/NvjYGC3
ymbIjOpHh/BDvJIkpRAGSvhhm3fButD8YOhQQsEAGkhAjG4dUVCZWOqBMxML9fAD
5jk4+IX9AgMBAAECggEABxR+a82Ps5gc2YdOnS5ngNzx5or4bV8IR4W3sLQiRbpj
REaJVzyf1SVrg+PgNZW8lO9Sq/0BqZjykETU4OFIUCcyX/eqTonqKD8ULOETwABV
vfiGGkDW5ha+m1Hl3SaW+M5tskVEEGizRUBQXMHuMPhF0Dpctj6MX03b6kde4fYl
wd+HZkkiS3oUuVA3k2+lCUcbpK0JfgETLumrj93KWsda+MZf+t7tl4tTekPrO0BR
KPJuxemXQA/jIpLzT/gaG/GxA/E39OOIGi56LA7GeO3I3S+MGozw8cRRaTPd98XQ
TU+ovO9lbBFhy0HypOsD+JfP1Y/QsfMv23nA5KZmtwKBgQD4hP9HErSrfbi3H+xV
Ng+Oi3QHCZHmV45uTiB96bxwx+W1n7AeBx0jBEohOGv01OaQPCieEROtXnrLFnyx
48ByOstcGHUlxLEKa4rlxNOdzteJB3NZxoIpx/sEEhGeyDGNLkn1O1ELD1E0ikZp
3herzhm+ld/U7YWcUlsLnl+Z9wKBgQD0YgMtBTMUEFD4Lp7Jo0cToPNj8bUI6yqY
e61Rw63BbSJyeBw8C4eCHTpFEm26c4p5n+iq0Z+r3Jnzx7iYfXu1PIgLd8V7r100
WPSyh7vY3lBQKLUqvgeQ1PoAXypRnZ082fvkdA/r5Ns+x00ejTygBidyPuw96OBZ
zWMTzy1CqwKBgQD1QSs8VLV/2B6GejadETDhF7Z1i3g0vYuOSAPAvv58volvaBxC
Rfr3J7CQgEHp6IFxLi1XcLreiTLdYV/FnmG5WVR/mpNhpm6hPehhQJEmV45VaMjp
fAHQgc6zAbHp5N8h2OCb5uHf7EnTc/JxYAA0SL0XXIj8dTs6PfwjxzPJmQKBgF9U
gIKmXZd9CejWXtCvZcGNboRVPFZ/Tf1veVvE5lnm1aIrom/122VxO1LIbo9mFOV+
8Ib6ALxM8K09ApBRmtlHBJbcoOevr78E2GdwNWHSzyeFya4jtNXVjrRoaxytTDH5
op4qfC979d6WZkn9tGGEJQ0W6Jb56dJ+ISEQF0rDAoGAGOdy6X+2o3JSiYLF3aq9
wmT0TZ3M+A3g9x3tFKvJfgrmgs026G4GRwfqsYVx9A+0PCWWZc1BDsLDfmGyxMhJ
Z1FGdCHAe0i6KhN1P4jaHXCUZpG3Dom4GGZnAoEuwyPtanabNkIZamwVZMRVmyGf
8/J9ZZ850OEk8aFpj4kt5l8=
-----END PRIVATE KEY-----
"""
client_email = "streamlit-user-auth@streamlit-user-auth.iam.gserviceaccount.com"
client_id = "111534329375212808043"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-user-auth%40streamlit-user-auth.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
